Logging
EpikCord/EpikCord.py pull request #82
Opened 2022-02-18 01:13 UTC by nav-github01001

## Description

Logging is on works so im saving this as draft

## Checklist

- [x] - All code changes have been tested, if any
- [ ] - The documentation has been updated accordingly for any code changes
- [x] - This PR fixes an already existing issue #32 
- [x] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [ ] - This PR fixes a bug
- [x] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [ ] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

## Additional context

2022-02-18 02:10 UTC, nav-github01001 commented
@TheUntraceable

2022-02-18 03:30 UTC, Jerry-py commented
Thanks for the work it's appreciated. Approved btw

2022-02-18 03:31 UTC, Jerry-py commented
I'll work on doc strings

2022-02-18 05:22 UTC, nav-github01001 commented
Sorry for 29 Commits

2022-02-18 16:37 UTC, TheUntraceable requested changes
Please add spaces for lines like `Details{data}` to `Details: {data}` please.

2022-02-20 12:03 UTC, TheUntraceable approved these changes

2022-02-20 12:05 UTC, TheUntraceable commented on EpikCord/__init__.py
> +        message_data = {
Please remove this. This will raise a `400` because that is invalid data to use "`None`"

2022-02-20 12:07 UTC, TheUntraceable commented on build/lib/EpikCord/managers/__init__.py
> +Some parts of the code is done by discord.py and their amazing team of contributors
But none of their contributors helped to this? This is a new feature we added. Unless we need to add his license to every part of code which may not be theirs?

2022-02-21 02:43 UTC, closed without merging